version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
jobs:
  update_data:
    docker:
      - image: circleci/python:latest
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install beautifulsoup4 joblib requests google-api-python-client google-auth-httplib2 google-auth-oauthlib fuzzywuzzy python-Levenshtein openskill
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            echo ${AUTH} | base64 --decode --ignore-garbage > auth.json
            python get_league.py
            #python ranking_br.py
            python link_gen_allfiles.py
            python append_smasgg_cache_to_players.py
            python update_json_files.py
            python match_states.py
            python calc_statistics.py
            python skill.py
            #python docs_after.py
            #python players_to_link.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin multigames
            git add .
            git commit -am "[skip ci] Full update ${DATE_TODAY}" || true
            git push origin multigames || true

  update_smashgg:
    docker:
      - image: circleci/python:latest
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install beautifulsoup4 joblib requests google-api-python-client google-auth-httplib2 google-auth-oauthlib fuzzywuzzy python-Levenshtein openskill
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            echo ${AUTH} | base64 --decode --ignore-garbage > auth.json
            python get_smashgg_user_data.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin multigames
            git add .
            git commit -am "[skip ci] Full update ${DATE_TODAY}" || true
            git push origin multigames || true

  get_next_tournaments:
    docker:
      - image: circleci/python:latest
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install beautifulsoup4 lxml joblib requests google-api-python-client google-auth-httplib2 google-auth-oauthlib fuzzywuzzy python-Levenshtein python-dateutil
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            echo ${AUTH} | base64 --decode --ignore-garbage > auth.json
            python get_next_tournaments.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin multigames
            git add .
            git commit -am "[skip ci] Update next tournaments ${DATE_TODAY}" || true
            git push origin multigames || true

  get_top_clips:
    docker:
      - image: circleci/python:latest
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requests
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            echo ${AUTH} | base64 --decode --ignore-garbage > auth.json
            python twitch.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin multigames
            git add .
            git commit -am "[skip ci] Update twitch clips ${DATE_TODAY}" || true
            git push origin multigames || true

  week_tournament_results:
    docker:
      - image: circleci/python:latest
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requests
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > credentials.json
            echo ${AUTH} | base64 --decode --ignore-garbage > auth.json
            python gen_week_tournament_results.py
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "joaorbezerra@hotmail.com"
            git config user.name "tournamentapibot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin multigames
            git add .
            git commit -am "[skip ci] Update twitch clips ${DATE_TODAY}" || true
            git push origin multigames || true

workflows:
  daily_data_update:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *"
          filters:
            branches:
              only:
                - multigames
    jobs:
      - update_data

  update_smashgg:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - multigames
    jobs:
      - update_smashgg

  get_next_tournaments:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - multigames
    jobs:
      - get_next_tournaments

  get_top_clips:
    triggers:
      - schedule:
          cron: "0 1 * * 0"
          filters:
            branches:
              only:
                - multigames
    jobs:
      - get_top_clips

  week_tournament_results:
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - multigames
    jobs:
      - week_tournament_results
